### ISSUE TITLE
Library doesn't work without rxjs-compat

### ISSUE THREAD

**Issue by lukasmatta** [abhazelton/animate-on-scroll#21]
After installation, I experienced an error described in #20 and it couldn't be solved by upgrading _rxjs_. I had to install _rxjs-compat_. Shouldn't it be included as a dependency then?

**Comment by abhazelton** [comment]
rxjs-compat is for backward compatibility, and I believe to allow for imports from old locations since those import locations changed for rxjs.  Thus, depending on the version of rxjs you have installed, I _think_ it may or may not be needed.  Someone can chime in if I'm off on that.

Sorry for the trouble you had and thanks for mentioning this, which could be helpful for others.  Closing this for now, comment back if it really should be added.

**Comment by BrendanBerkley** [comment]
Not sure if this needs a data point, but I just added `"ng2-animate-on-scroll": "^1.0.11",` to my repo with `"rxjs": "^6.3.3",`, and I needed to add rxjs-compat to my package.json in order to get the project running.
